[package]
name = "benchmark_joins"
version = "0.1.0"
authors = ["Amir Fahat <amirf@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"